### ISSUE TITLE
Import location function needs for duckewiki

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio-r#12]
The import location function is not yet configured to import plot data: startx, starty, dimx, dimy, for example. I will need this to import the duckewiki data.
Also, it would be nice if could retrieve easily, after the import job is concluded, the id of the imported entity. As a return of the function or a check_ids_of_submitted_job like funcion, which would retrieve ids for imported locations (or else) and also ids for those that were not imported because they were already there. For example, I will need to first import all administrative level data, then import gazetteers from the duckewiki data.  I see the function identifies parent by geometry if not present and by name identify if present (but duplicate names may be allowed if in different localities, after all we may have the same local name for two distant localities). Hence, when geometry is not present, it would be nice to be able to inform directly the parentid to avoid such confusion.  This could be an additional parameter in the function.

**Comment by andrechalom** [comment]
Yes, you´re right. I need to update the code to allow for startx / dimx,
etc. This is a top priority issue.

For returning the IDs, I can set the server to add log messages such as
"Location Cananéia successfully imported with ID 14", would this be enough?

On Fri, Jan 26, 2018 at 5:02 PM, Alberto Vicentini <notifications@github.com

**Comment by andrechalom** [comment]
Finally, regarding this last sentences:

> I see the function identifies parent by geometry if not present and by name identify if present (but duplicate names may be allowed if in different localities, after all we may have the same local name for two distant localities). Hence, when geometry is not present, it would be nice to be able to inform directly the parentid to avoid such confusion. This could be an additional parameter in the function.

It is already possible to specify the parent id of an imported location. It is even possible to mix some locations with a declared parent, and some locations which should be auto-guessed in the same job.

**Comment by andrechalom** [comment]
Adding support for x, y, startx, starty on OpenDataBio server version 0.7.3. The R package does not need to be updated. Please check the API documentation at https://github.com/opendatabio/opendatabio/wiki/API-v0-endpoints#locations to make sure that all relevant fields are now included.
