### ISSUE TITLE
Batch use of odb_get functions - connection overload

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio-r#19]
I am getting the following erros after using the odb_get_location and odb_import location in batch mode:
```
Error in odb_send_get(params, odb_cfg, "locations") : 
  Too Many Requests (RFC 6585) (HTTP 429).
```
Should the odb_send_get function include a close() connection line after each attempt. Or else, how to avoid this in R. Tried looking but found only shortcuts like placing a Sys.Sleep within the loop to wait for connection to close automatically, but seems not working.

**Comment by andrechalom** [comment]
Please provide a reproducible example. What are you trying to do?

**Comment by betovicentini** [comment]
I was trying to check whether a locality was present, using sapply with the following function:

```
checalocal <- function(x,prid=prid) {
  #cat("\014")
  pid = prid[x]
  print(paste(x,pid))
  pr = odb_params(list(search=URLencode(x),parent_id=pid))
  ll = odb_get_locations(pr,cfg)
  Sys.sleep(1)
  if (length(ll)==1) {
    return(ll$id[[1]])
  } else {
    if (length(ll)>1) {
      print(paste(x,"in",prid,"has multiple hits"))
      print(ll[,-3])
    }
    return(NA)
  }
}
```
This goes over all municipalities, for example, of a GDAM file.

**Comment by andrechalom** [comment]
First: This is a function that should be incorporated in the package (along
with similar functions for taxon, person, etc). However it's very hard for
me to understand how to use this. What does prid mean? How is this function
supposed to be called?

Second: the API is designed to prevent a single user from using all of the
possible connections (which would cause a denial of service for other users
attempting to reach the server). So the error HTTP 429 is expected if you
run so many queries in quick succession - the counter of requests per IP is
reset every minute. Please check the API documentation about this on our
wiki.

I believe the best way to handle this is by having a function in the
package that takes a list of names and makes a single query to the server.
The ability to serve this must be implemented on the server side.

Finally, URLencode is already used by default in version 0.1.6 of the R
package.

**Comment by andrechalom** [comment]
Closing as the error reported is intended behavior.
