### ISSUE TITLE
Problems importing GADM admin data - ADMIN LEVEL

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio-r#22]
I tried importing data from GADM, including all subdivisions of a country. Used Bolivia as a test, whose data goes from ADM_LEVEL=0 to ADM_LEVEL=3. The following issues were found:

- Admin_level=1 and 2,  are `Department` and `Province`, respectively, while Admin_Level 3 is `Municipality`. Opendatabio recognizes admin_level 2 as municipality and 1 as state. This is because in Brazil we have only two subdivisions, but in most SA countries there are three and sometimes four. So we cannot use the Brazil case as an example to assign levelName for admin units.
- Either we need to inform this during importation, but then the same level may have different names depending on country. 
- Or else, we simplify and use generic categories like MAJORAREA (Department or State), MAJORAREA2 (Province) and MINORAREA (Municipality), 
- Admin3 for Bolivia was labeled `levels.adm.3` by opendatabio. However, when editing a record imported like that, the administrative level shown is `Country`.

[EDIT: replaced "GDAM" by GADM @andrechalom]

**Comment by andrechalom** [comment]
I agree that using major area / minor area is a good idea. Will change this
soon.

For the bugs, the use of adm level 3 needs to be configured on
config/app.php file. Thisis relevant as GADM uses up to 6 levels deep, but
most countries don't use all of this.

**Comment by betovicentini** [comment]
Ok, but changing app.php is not ideal. We need a flexible tool, perhaps a simple code table in the R package to precode before importation.

**Comment by andrechalom** [comment]
I respectufully disagree. This configuration, along with time zone,
tropicos api key, proxy, etc, is something that will need to be done only
once for a given odb install. If you really need this in the interface,
please open a separate issue for this, but this is certainly beyond the
scope of the current project.

**Comment by andrechalom** [comment]
Changed the names for "Administrative Area 1" to "Administrative Area 6" in the server repository, as there's no way to tell if a level 2 should be "major area 2" or "minor area".
