### ISSUE TITLE
affected_ids should return something for non-imported records

### ISSUE THREAD

**Issue by betovicentini** [opendatabio/opendatabio-r#24]
The ''affected_ids'' function returns only the ids for the imported records, but it is impossible to use it if some records in the data.frame being imported are not imported for some reason (found already or error). So, it would be important that the affected_ids return:
1. the ids of the new record imported 
2. the ids for records that were found in the database and hence not imported again
3. NA for the records that could not be imported due to some errors
With this, for any importation to the data.base, one would get the full list of ids and NAs would directly indicate which records were not imported.

**Comment by andrechalom** [comment]
Fixed in https://github.com/opendatabio/opendatabio/issues/215
