### ISSUE TITLE
Numeric vs Integer

### ISSUE THREAD

**Issue by birutaibm** [opendatabio/opendatabio-r#27]
Please, replace the line 278 of utils.R from `if (class(job) == "numeric" && length(job) == 1)` to `if (is.numeric(job) && length(job) == 1)`. If class(job) is integer the first command gives false, but the other gives true.

**Comment by andrechalom** [comment]
Correct! R is actually quite strange when handling integer numbers. It can use "numeric" or "integer class", but both return true to `is.numeric`, see:
```R
> class(1)
[1] "numeric"
> class(1:2)
[1] "integer"
> is.numeric(1)
[1] TRUE
> is.numeric(1:2)
[1] TRUE
```
